Repository apache/thrift, pull requests merged in 2018-12, with the labels that each got.

#1618 THRIFT-4656: Fix infinite loop in PHP TCurlClient
  lib/php/lib/Transport/TCurlClient.php
Labels: bugfix

#1650 THRIFT-4426: remove a symbolic link that was checked in
  tutorial/erl/server.sh
Labels: cosmetic

#1652 Update Cargo.toml, release instructions and release script
  lib/rs/Cargo.toml
  lib/rs/RELEASING.md
  lib/rs/release.sh
Labels: ci

#1651 THRIFT-4546: replace all git-wip-us.apache.org
  bower.json
  contrib/fb303/java/build.xml
  debian/control
  doap.rdf
  doc/committers.md
  doc/install/centos.md
  doc/specs/idl.md
  lib/as3/build.xml
  lib/java/gradle/publishing.gradle
  lib/js/test/test-deep-constructor.html
  lib/js/test/test-es6.html
  lib/js/test/test-nojq.html
  lib/js/test/test.html
  lib/js/test/testws.html
  package.json
  sonar-project.properties
  tutorial/js/tutorial.html
Labels: cosmetic

#1654 THRIFT-4690: update bionic docker image to use upstream deimos OpenSSL 1.1 tag for dlang
  build/docker/ubuntu-bionic/Dockerfile
Labels: ci
