Repository apache/thrift, pull requests merged in 2019-03, with the labels that each got.

#1748 THRIFT-4811: Add CMake config file and targets. (see #4752)
  CMakeLists.txt
  build/cmake/DefineInstallationPaths.cmake
  build/cmake/GenerateConfigModule.cmake
  build/cmake/ThriftConfig.cmake.in
  build/cmake/ThriftMacros.cmake
Labels: releng

#1763 Fix xenial and bump go version on bionic
  build/docker/ubuntu-bionic/Dockerfile
  build/docker/ubuntu-xenial/Dockerfile
Labels: ci

#1755 [RS] Add clarification of where a constant comes from
  tutorial/rs/src/bin/tutorial_client.rs
Labels: cosmetic
