Repository apache/thrift, pull requests merged in 2019-01, with the labels that each got.

#1661 remove unused travis build files
  build/travis/installCXXDependencies.sh
  build/travis/installDependencies.sh
Labels: ci

#1665 THRIFT-4713: Review of TBaseHelper
  lib/java/src/org/apache/thrift/TBaseHelper.java
Labels: optimization

#1660 THRIFT-4547: add swift to bionic build image and run unit tests
  .gitignore
  build/docker/ubuntu-bionic/Dockerfile
  configure.ac
  lib/Makefile.am
  lib/swift/Makefile.am
  lib/swift/README.md
Labels: ci

#1667 THRIFT-4301: fix inability to disable py3 with autoconf build
  configure.ac
Labels: bugfix

#1658 THRIFT-4702: Improve AutoExpandingBuffer
  lib/java/README.md
  lib/java/src/org/apache/thrift/transport/AutoExpandingBuffer.java
  lib/java/src/org/apache/thrift/transport/AutoExpandingBufferReadTransport.java
  lib/java/src/org/apache/thrift/transport/AutoExpandingBufferWriteTransport.java
  lib/java/src/org/apache/thrift/transport/TFastFramedTransport.java
  lib/java/test/org/apache/thrift/transport/TestAutoExpandingBuffer.java
  lib/java/test/org/apache/thrift/transport/TestAutoExpandingBufferReadTransport.java
  lib/java/test/org/apache/thrift/transport/TestAutoExpandingBufferWriteTransport.java
Labels: optimization

#1672 THRIFT-4481: TBinaryProtocol.writeMessageEnd does not allow throwable…
  lib/java/src/org/apache/thrift/protocol/TBinaryProtocol.java
  lib/java/src/org/apache/thrift/protocol/TCompactProtocol.java
  lib/java/src/org/apache/thrift/protocol/TSimpleJSONProtocol.java
Labels: bugfix

#1664 THRIFT-4712: Improve Performance of ShortStack
  lib/java/README.md
  lib/java/src/org/apache/thrift/protocol/ShortStack.java
  lib/java/src/org/apache/thrift/protocol/TCompactProtocol.java
  lib/java/test/org/apache/thrift/TestShortStack.java
  lib/java/test/org/apache/thrift/protocol/TestShortStack.java
Labels: optimization

#1671 THRIFT-4714: optimize java TFramedTransports to call write only once per flush
  lib/java/src/org/apache/thrift/transport/AutoExpandingBufferWriteTransport.java
  lib/java/src/org/apache/thrift/transport/TFastFramedTransport.java
  lib/java/src/org/apache/thrift/transport/TFramedTransport.java
  lib/java/test/org/apache/thrift/transport/TestAutoExpandingBufferWriteTransport.java
  lib/java/test/org/apache/thrift/transport/TestTFramedTransport.java
Labels: optimization

#1676 update language levels in docker build image (bionic) and readmes
  LANGUAGES.md
  build/docker/README.md
  build/docker/ubuntu-bionic/Dockerfile
Labels: ci, doc

#1679 THRIFT-4726: Remove SLF4J Logging Guards
  lib/java/src/org/apache/thrift/server/TThreadPoolServer.java
  lib/java/src/org/apache/thrift/transport/TSaslTransport.java
Labels: optimization

#1680 THRIFT-4728: automate the double rendering test
  lib/js/Gruntfile.js
  lib/js/test/test-double-rendering.html
  lib/js/test/test-double-rendering.js
Labels: testsuite

#1682 THRIFT-4697: Add release management docs to GitHub [ci skip]
  doc/ReleaseManagement.md
Labels: doc

#1687 THRIFT-4732: windows cmake refinements and add windows docker build support
  CMakeLists.txt
  appveyor.yml
  build/appveyor/CYGW-appveyor-build.bat
  build/appveyor/MING-appveyor-build.bat
  build/appveyor/MSVC-appveyor-build.bat
  build/appveyor/cl_setenv.bat
  build/cmake/DefineOptions.cmake
  build/cmake/DefinePlatformSpecifc.cmake
  build/cmake/README.md
  build/cmake/ThriftMacros.cmake
  build/docker/msvc2017/Dockerfile
  build/docker/msvc2017/README.md
  build/docker/msvc2017/build-compiler.bat
  build/docker/msvc2017/build.bat
  build/wincpp/README.md
  build/wincpp/build-thrift-compiler.bat
  build/wincpp/build-thrift.bat
  build/wincpp/scripts/cl_setarch.bat
  build/wincpp/scripts/cl_setcompiler.bat
  build/wincpp/scripts/cl_setgenerator.bat
  build/wincpp/scripts/tpversions.bat
  build/wincpp/thirdparty/src/build-libevent.bat
  build/wincpp/thirdparty/src/build-openssl.bat
  build/wincpp/thirdparty/src/build-zlib.bat
  compiler/cpp/CMakeLists.txt
  compiler/cpp/test/CMakeLists.txt
  lib/cpp/CMakeLists.txt
  lib/cpp/README.md
  lib/cpp/src/thrift/TOutput.cpp
  lib/cpp/src/thrift/TOutput.h
  lib/cpp/src/thrift/protocol/TJSONProtocol.cpp
Labels: enhancement

#1689 THRIFT-4735: Remove Qt4 build support
  CHANGES.md
  build/cmake/DefineOptions.cmake
  build/cmake/DefinePlatformSpecifc.cmake
  build/veralign.sh
  compiler/cpp/src/thrift/main.cc
  configure.ac
  contrib/Vagrantfile
  lib/cpp/CMakeLists.txt
  lib/cpp/Makefile.am
  lib/cpp/README.md
  lib/cpp/test/CMakeLists.txt
  lib/cpp/thrift-qt.pc.in
  lib/swift/Tests/ThriftTests/ThriftTests.swift
Labels: enhancement

#1691 Fix cygwin builds on appveyor
  appveyor.yml
  build/appveyor/CYGW-appveyor-build.bat
  build/appveyor/CYGW-appveyor-install.bat
Labels: ci

#1693 THRIFT-4487: replace gettimeofday implementation on windows
  lib/cpp/src/thrift/windows/GetTimeOfDay.cpp
Labels: bugfix

#1695 THRIFT-4691: ensure CPAN module runs unit tests
  configure.ac
  lib/perl/MANIFEST.SKIP
  lib/perl/Makefile.PL
  lib/perl/Makefile.am
  lib/perl/build-cpan-dist.sh
  lib/perl/t/Makefile.am
  lib/perl/t/memory_buffer.t
  lib/perl/t/multiplex.t
  lib/perl/t/processor.t
Labels: bugfix

#1700 THRIFT-4163: update cmake build type handling
  build/cmake/BuildType.cmake
  build/cmake/DefineCMakeDefaults.cmake
  build/cmake/DefineOptions.cmake
  lib/csharp/src/Protocol/TProtocolException.cs
  lib/csharp/src/TException.cs
  lib/hs/CMakeLists.txt
Labels: ci

#1702 THRIFT-4746: changes for publishing 0.12.0 to maven (WORKING ON CROSS TEST DART FAILURES)
  .travis.yml
  lib/java/CMakeLists.txt
  lib/java/README.md
  lib/java/build.gradle
  lib/java/gradle.properties
  lib/java/gradle/publishing.gradle
  lib/java/gradle/wrapper/gradle-wrapper.properties
  test/dart/test_client/bin/main.dart
  test/tests.json
Labels: releng

#1708 THRIFT-4751: Missing imports in TProtocol (phpdoc related only)
  lib/php/lib/Protocol/TProtocol.php
Labels: cosmetic

#1706 THRIFT-4750: as3 changes to build and publish to maven central
  .gitignore
  CMakeLists.txt
  LANGUAGES.md
  build/cmake/DefineOptions.cmake
  build/docker/README.md
  build/docker/ubuntu-bionic/Dockerfile
  build/veralign.sh
  compiler/cpp/README.md
  configure.ac
  doc/ReleaseManagement.md
  lib/Makefile.am
  lib/as3/CMakeLists.txt
  lib/as3/Makefile.am
  lib/as3/README.md
  lib/as3/build.gradle
  lib/as3/build.properties
  lib/as3/build.xml
  lib/as3/gradle.properties
  lib/as3/gradle/publishing.gradle
  lib/as3/gradle/wrapper/gradle-wrapper.jar
  lib/as3/gradle/wrapper/gradle-wrapper.properties
  lib/as3/gradlew
  lib/as3/gradlew.bat
  lib/as3/settings.gradle
  test/tests.json
Labels: ci, releng

#1703 THRIFT-4675: Fix i64 map key generation for js
  compiler/cpp/src/thrift/generate/t_js_generator.cc
  lib/js/package.json
  lib/js/test/test-int64.html
  lib/js/test/test-int64.js
  lib/nodejs/test/int64.test.js
  lib/nodets/test/int64.test.ts
  lib/ts/package.json
  lib/ts/test/test-int64.ts
  package-lock.json
  package.json
  test/Int64Test.thrift
Labels: bugfix

#1715 THRIFT-4757: fix npm identified security vulnerability in transient dependency on sync-exec
  build/veralign.sh
  lib/js/package-lock.json
  lib/js/package.json
  lib/ts/Makefile.am
  lib/ts/package-lock.json
  lib/ts/package.json
Labels: security

#1720 THRIFT-4763: HTML compiler produces invalid HTML document
  compiler/cpp/src/thrift/generate/t_html_generator.cc
  package-lock.json
  package.json
  test/Makefile.am
Labels: bugfix
