Repository apache/thrift, pull requests merged in 2019-02, with the labels that each got.

#1725 THRIFT-4767: Added TSocket/TSSLSocket support tcp keep-alive in python
  lib/py/src/transport/TSSLSocket.py
  lib/py/src/transport/TSocket.py
Labels: enhancement

#1723 THRIFT-4766: Fix JDK11 build
  build/docker/ubuntu-bionic/Dockerfile
  debian/control
  lib/java/gradle.properties
  lib/java/gradle/environment.gradle
Labels: bugfix

#1728 fix minor glib warning
  lib/c_glib/src/thrift/c_glib/transport/thrift_socket.c
Labels: cosmetic

#1714 THRIFT-4759:add thrift export to fix windows shared lib building
  appveyor.yml
  lib/cpp/CMakeLists.txt
  lib/cpp/Makefile.am
  lib/cpp/src/thrift/TOutput.cpp
  lib/cpp/src/thrift/TOutput.h
  lib/cpp/src/thrift/thrift_export.h
  lib/cpp/src/thrift/transport/TSSLServerSocket.cpp
  lib/cpp/src/thrift/transport/TSSLSocket.h
Labels: releng

#1688 THRIFT-4732:refine cmake scripts
  CMakeLists.txt
  build/cmake/DefinePlatformSpecifc.cmake
  build/cmake/FindClangTools.cmake
  build/cmake/StaticCodeAnalysis.cmake
  lib/c_glib/CMakeLists.txt
  lib/c_glib/src/thrift/c_glib/protocol/thrift_multiplexed_protocol.c
  lib/c_glib/src/thrift/c_glib/transport/thrift_ssl_socket.c
  test/c_glib/CMakeLists.txt
Labels: releng

#1734 THRIFT-4778: fix inheritance for protocol factories
  lib/py/src/protocol/TBinaryProtocol.py
  lib/py/src/protocol/TCompactProtocol.py
  lib/py/src/protocol/THeaderProtocol.py
  lib/py/src/protocol/TJSONProtocol.py
Labels: bugfix

#1735 THRIFT-4779: fix exception type in TMultiplexedProcessor
  lib/java/src/org/apache/thrift/TMultiplexedProcessor.java
  lib/py/src/TMultiplexedProcessor.py
Labels: bugfix

#1736 THRIFT-4780: finish the server implementation of multiplexed in python test server
  lib/py/src/TMultiplexedProcessor.py
  lib/py/src/protocol/__init__.py
  test/known_failures_Linux.json
  test/py/TestClient.py
  test/py/TestServer.py
  test/rs/src/bin/test_client.rs
  test/tests.json
Labels: enhancement, testsuite

#1737 THRIFT-4784 Thrift should throw when skipping over unexpected data
  lib/as3/src/org/apache/thrift/protocol/TProtocolUtil.as
Labels: bugfix

#1739 THRIFT-4794: finish php json cross test
  build/docker/ubuntu-bionic/Dockerfile
  build/docker/ubuntu-xenial/Dockerfile
  test/php/Makefile.am
  test/php/test_php.ini
  test/tests.json
Labels: testsuite

#1738 THRIFT-4798: fix py/py3 server, java client with http transport
  compiler/cpp/src/thrift/generate/t_py_generator.cc
  lib/java/test/org/apache/thrift/test/TestClient.java
  lib/py/src/TMultiplexedProcessor.py
  lib/py/src/Thrift.py
  lib/py/src/server/THttpServer.py
  test/known_failures_Linux.json
Labels: bugfix

#1742 THRIFT-4024, THRIFT-4783: throw when skipping invalid type
  lib/c_glib/src/thrift/c_glib/protocol/thrift_protocol.c
  lib/cpp/src/thrift/protocol/TProtocol.h
  lib/d/src/thrift/protocol/base.d
  lib/dart/lib/src/protocol/t_protocol_util.dart
  lib/go/thrift/protocol.go
  lib/javame/src/org/apache/thrift/protocol/TProtocolUtil.java
  lib/js/src/thrift.js
  lib/lua/TProtocol.lua
  lib/nodejs/lib/thrift/binary_protocol.js
  lib/nodejs/lib/thrift/compact_protocol.js
  lib/nodejs/lib/thrift/json_protocol.js
  lib/ocaml/src/Thrift.ml
  lib/py/src/protocol/TProtocol.py
  lib/rb/lib/thrift/protocol/base_protocol.rb
  lib/rb/spec/base_protocol_spec.rb
  lib/swift/Sources/TProtocol.swift
Labels: bugfix

#1741 THRIFT-4768 Remove "nullable" option from the code base (netstd ONLY)
  compiler/cpp/src/thrift/generate/t_netstd_generator.cc
  compiler/cpp/src/thrift/generate/t_netstd_generator.h
Labels: optimization

#1743 [THRIFT-4771] add nodejs THeaderProtocol support
  lib/nodejs/lib/thrift/binary_protocol.js
  lib/nodejs/lib/thrift/buffered_transport.js
  lib/nodejs/lib/thrift/framed_transport.js
  lib/nodejs/lib/thrift/header_protocol.js
  lib/nodejs/lib/thrift/header_transport.js
  lib/nodejs/lib/thrift/index.js
  lib/nodejs/lib/thrift/server.js
  lib/nodejs/test/header.test.js
  lib/nodejs/test/helpers.js
  lib/nodejs/test/test_header_payload
  test/features/known_failures_Linux.json
  test/known_failures_Linux.json
  test/tests.json
Labels: enhancement
