Repository apache/thrift, pull requests merged in 2022-11, with the labels that each got.

#2724 Use multi-module to cleanup top level go.mod
  .github/workflows/build.yml
  go.mod
  lib/go/Makefile.am
  lib/go/test/Makefile.am
  lib/go/test/fuzz/Makefile.am
  lib/go/test/go.mod
  lib/go/test/go.sum
  lib/go/test/tests/thrifttest_handler.go
  test/go/Makefile.am
  test/go/genmock.sh
  test/go/go.mod
  test/go/go.sum
  tutorial/go/Makefile.am
Labels: golang

#2719 THRIFT-5657: Use Swift 5.7 in all CI (github actions + travis)
  LANGUAGES.md
  build/docker/ubuntu-bionic/Dockerfile
  build/docker/ubuntu-focal/Dockerfile
  build/docker/ubuntu-jammy/Dockerfile
Labels: swift

#2722 THRIFT-5663: lib: cpp: usleep was not declared in this scope
  lib/cpp/src/thrift/transport/TFDTransport.cpp
  lib/cpp/src/thrift/transport/TFileTransport.cpp
Labels: c++

#2723 THRIFT-5666: lib: cpp: prefer poll.h over sys/poll.h
  lib/cpp/src/thrift/transport/TNonblockingServerSocket.cpp
  lib/cpp/src/thrift/transport/TSSLSocket.cpp
  lib/cpp/src/thrift/transport/TServerSocket.cpp
  lib/cpp/src/thrift/transport/TSocket.cpp
Labels: c++

#2689 THRIFT-5660: lib: cpp: TTransportException: create thrift::numeric_cast
  lib/cpp/src/thrift/numeric_cast.h
  lib/cpp/src/thrift/transport/TTransportException.h
Labels: c++
