Repository apache/thrift, pull requests merged in 2022-10, with the labels that each got.

#2710 fix various java codestyle issues
  lib/java/src/main/java/org/apache/thrift/TAsyncProcessor.java
  lib/java/src/main/java/org/apache/thrift/TBase.java
  lib/java/src/main/java/org/apache/thrift/TEnum.java
  lib/java/src/main/java/org/apache/thrift/TEnumHelper.java
  lib/java/src/main/java/org/apache/thrift/TFieldIdEnum.java
  lib/java/src/main/java/org/apache/thrift/TFieldRequirementType.java
  lib/java/src/main/java/org/apache/thrift/TNonblockingMultiFetchClient.java
  lib/java/src/main/java/org/apache/thrift/TNonblockingMultiFetchStats.java
  lib/java/src/main/java/org/apache/thrift/TProcessor.java
  lib/java/src/main/java/org/apache/thrift/TSerializable.java
  lib/java/src/main/java/org/apache/thrift/TSerializer.java
  lib/java/src/main/java/org/apache/thrift/TServiceClientFactory.java
  lib/java/src/main/java/org/apache/thrift/async/TAsyncClient.java
  lib/java/src/main/java/org/apache/thrift/async/TAsyncClientFactory.java
  lib/java/src/main/java/org/apache/thrift/async/TAsyncClientManager.java
  lib/java/src/main/java/org/apache/thrift/async/TAsyncMethodCall.java
  lib/java/src/main/java/org/apache/thrift/partial/EnumCache.java
  lib/java/src/main/java/org/apache/thrift/protocol/TBase64Utils.java
  lib/java/src/main/java/org/apache/thrift/protocol/TJSONProtocol.java
  lib/java/src/main/java/org/apache/thrift/protocol/TProtocolDecorator.java
  lib/java/src/main/java/org/apache/thrift/protocol/TSimpleJSONProtocol.java
  lib/java/src/main/java/org/apache/thrift/protocol/TTupleProtocol.java
  lib/java/src/main/java/org/apache/thrift/scheme/IScheme.java
  lib/java/src/main/java/org/apache/thrift/scheme/SchemeFactory.java
  lib/java/src/main/java/org/apache/thrift/server/AbstractNonblockingServer.java
  lib/java/src/main/java/org/apache/thrift/server/Invocation.java
  lib/java/src/main/java/org/apache/thrift/server/TExtensibleServlet.java
  lib/java/src/main/java/org/apache/thrift/server/TNonblockingServer.java
  lib/java/src/main/java/org/apache/thrift/server/TServlet.java
  lib/java/src/main/java/org/apache/thrift/server/TSimpleServer.java
  lib/java/src/main/java/org/apache/thrift/server/TThreadPoolServer.java
  lib/java/src/main/java/org/apache/thrift/server/TThreadedSelectorServer.java
  lib/java/src/main/java/org/apache/thrift/transport/TSSLTransportFactory.java
  lib/java/src/main/java/org/apache/thrift/transport/TSimpleFileTransport.java
  lib/java/src/main/java/org/apache/thrift/transport/layered/TFramedTransport.java
  lib/java/src/main/java/org/apache/thrift/transport/layered/TLayeredTransport.java
  lib/java/src/main/java/org/apache/thrift/transport/sasl/DataFrameWriter.java
  lib/java/src/main/java/org/apache/thrift/transport/sasl/NonblockingSaslHandler.java
Labels: java

#2708 THRIFT-5650: Implement UUID in Go library
  .github/workflows/build.yml
  LANGUAGES.md
  build/docker/ubuntu-bionic/Dockerfile
  build/docker/ubuntu-jammy/Dockerfile
  go.mod
  go.sum
  lib/go/test/tests/protocol_mock.go
  lib/go/thrift/binary_protocol.go
  lib/go/thrift/compact_protocol.go
  lib/go/thrift/debug_protocol.go
  lib/go/thrift/duplicate_protocol.go
  lib/go/thrift/header_protocol.go
  lib/go/thrift/json_protocol.go
  lib/go/thrift/pointerize.go
  lib/go/thrift/protocol.go
  lib/go/thrift/protocol_test.go
  lib/go/thrift/simple_json_protocol.go
  lib/go/thrift/type.go
  lib/go/thrift/uuid.go
  lib/go/thrift/uuid_test.go
Labels: golang

#2687 THRIFT-5659: lib: cpp: protocol: declare when methods override
  lib/cpp/src/thrift/protocol/TBinaryProtocol.h
  lib/cpp/src/thrift/protocol/TCompactProtocol.h
  lib/cpp/src/thrift/protocol/TJSONProtocol.h
Labels: c++

#2718 THRIFT-5650: Implement UUID in Go compiler
  compiler/cpp/src/thrift/generate/t_go_generator.cc
  compiler/cpp/src/thrift/generate/validator_parser.cc
  lib/go/test/EqualsTest.thrift
  lib/go/test/tests/equals_test.go
  lib/go/thrift/json_protocol.go
  test/ConstantsDemo.thrift
  test/go/Makefile.am
  test/go/src/bin/testclient/main.go
  test/go/src/common/clientserver_test.go
  test/go/src/common/printing_handler.go
  test/go/src/common/simple_handler.go
Labels: golang
