Repository apache/thrift, pull requests merged in 2023-07, with the labels that each got.

#2782 THRIFT-5671: return dependencies to POM
  lib/java/gradle/publishing.gradle
Labels: java

#2825 Convert string types to Enums in Struct py:enum gen code
  compiler/cpp/src/thrift/generate/t_py_generator.cc
  test/py/explicit_module/EnumSerializationTest.py
  test/py/explicit_module/runtest.sh
  test/py/explicit_module/test5.thrift
Labels: python

#2816 THRIFT-5715: Python non-user defined fields mutable with slots
  compiler/cpp/src/thrift/generate/t_py_generator.cc
  test/py/TestClient.py
Labels: python

#2832 Setting TCP_ NODELAY option for rust server
  lib/rs/src/server/threaded.rs
Labels: rust

#2833 THRIFT-5726 package upgrades and consolidation/improvement of build targets checks
  lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj
  lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj
  lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
  lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj
  lib/netstd/Thrift/Protocol/TJSONProtocol.cs
  lib/netstd/Thrift/Thrift.csproj
  lib/netstd/Thrift/Transport/Client/THttpTransport.cs
  lib/netstd/Thrift/Transport/Client/TNamedPipeTransport.cs
  lib/netstd/Thrift/Transport/Client/TStreamTransport.cs
  lib/netstd/Thrift/Transport/Server/TNamedPipeServerTransport.cs
  test/netstd/Client/Client.csproj
  test/netstd/Server/Server.csproj
  tutorial/netstd/Interfaces/Interfaces.csproj
  tutorial/netstd/Server/Server.csproj
Labels: c#
