Repository apache/thrift, pull requests merged in 2023-03, with the labels that each got.

#2739 THRIFT-5674: Catch and handle server implementation exceptions
  compiler/cpp/src/thrift/generate/t_js_generator.cc
  tutorial/nodejs/NodeClientPromise.js
Labels: javascript

#2770 py TSocket: Only disable socket.IPV6_V6ONLY when the family is AF_INET6
  lib/py/src/transport/TSocket.py
Labels: python

#2768 Add missing include for the security tests
  lib/cpp/test/SecurityFromBufferTest.cpp
  lib/cpp/test/SecurityTest.cpp
Labels: c++

#2771 THRIFT-5692 Support for deprecated methods (via annotation) for haxe targets
  compiler/cpp/src/thrift/generate/t_haxe_generator.cc
Labels: haxe
