Repository apache/thrift, pull requests merged in 2023-10, with the labels that each got.

#2863 fix(php): exclude most part of the repo for php package
  composer.json
Labels: php

#2864 lib/cpp/test/Security*Test.cpp: Fix the check for OpenSSL version macro
  lib/cpp/test/SecurityFromBufferTest.cpp
  lib/cpp/test/SecurityTest.cpp
Labels: c++

#2866 Very minor code cleanup (whitespace changes only)
  lib/cpp/test/concurrency/Tests.cpp
Labels: c++

#2868 Do not install `FindLibevent.cmake` when libevent is disabled
  build/cmake/GenerateConfigModule.cmake
Labels: build

#2869 [ci] use gradle 8.4 (trivial build env change)
  .github/workflows/build.yml
  build/docker/old/ubuntu-disco/Dockerfile
  build/docker/old/ubuntu-xenial/Dockerfile
  build/docker/ubuntu-bionic/Dockerfile
  build/docker/ubuntu-focal/Dockerfile
  build/docker/ubuntu-jammy/Dockerfile
  doc/install/README.md
  doc/install/debian.md
  lib/java/README.md
Labels: ci

#2732 THRIFT-5670: lib: cpp: Fix wrong timeout error message
  lib/cpp/src/thrift/transport/TSocket.cpp
Labels: c++
