Repository apache/thrift, pull requests merged in 2023-11, with the labels that each got.

#2870 THRIFT-5741: use rust 1.65
  .github/workflows/build.yml
  LANGUAGES.md
  build/docker/README.md
  build/docker/old/ubuntu-disco/Dockerfile
  build/docker/old/ubuntu-xenial/Dockerfile
  build/docker/ubuntu-bionic/Dockerfile
  build/docker/ubuntu-focal/Dockerfile
  build/docker/ubuntu-jammy/Dockerfile
  lib/rs/README.md
  lib/rs/src/protocol/binary.rs
  lib/rs/src/protocol/compact.rs
  lib/rs/src/server/multiplexed.rs
  lib/rs/test/src/bin/kitchen_sink_server.rs
  rust-toolchain
  test/rs/src/bin/test_server.rs
Labels: rust

#2881 THRIFT-5743 add TLS1.3 to default protocols where available
  lib/netstd/Thrift/Transport/Client/TTlsSocketTransport.cs
  lib/netstd/Thrift/Transport/Server/TTlsServerSocketTransport.cs
  test/netstd/Client/TestClient.cs
  test/netstd/Server/TestServer.cs
Labels: c#

#2885 THRIFT-5746 Upgrade to net8
  build/docker/old/debian-stretch/Dockerfile
  build/docker/old/ubuntu-artful/Dockerfile
  build/docker/old/ubuntu-disco/Dockerfile
  build/docker/old/ubuntu-xenial/Dockerfile
  build/docker/ubuntu-bionic/Dockerfile
  build/docker/ubuntu-focal/Dockerfile
  build/docker/ubuntu-jammy/Dockerfile
  compiler/cpp/src/thrift/generate/t_netstd_generator.cc
  compiler/cpp/src/thrift/generate/t_netstd_generator.h
  lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj
  lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj
  lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
  lib/netstd/Tests/Thrift.Tests/Collections/TCollectionsTests.cs
  lib/netstd/Tests/Thrift.Tests/DataModel/DeepCopy.cs
  lib/netstd/Tests/Thrift.Tests/DataModel/NullValuesSet.cs
  lib/netstd/Tests/Thrift.Tests/Protocols/TJsonProtocolHelperTests.cs
  lib/netstd/Tests/Thrift.Tests/Protocols/TJsonProtocolTests.cs
  lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj
  lib/netstd/Thrift/.editorconfig
  lib/netstd/Thrift/Processor/TMultiplexedProcessor.cs
  lib/netstd/Thrift/Processor/TSingletonProcessorFactory.cs
  lib/netstd/Thrift/Protocol/Entities/TField.cs
  lib/netstd/Thrift/Protocol/Entities/TList.cs
  lib/netstd/Thrift/Protocol/Entities/TMap.cs
  lib/netstd/Thrift/Protocol/Entities/TMessage.cs
  lib/netstd/Thrift/Protocol/Entities/TSet.cs
  lib/netstd/Thrift/Protocol/Entities/TStruct.cs
  lib/netstd/Thrift/Protocol/TBinaryProtocol.cs
  lib/netstd/Thrift/Protocol/TCompactProtocol.cs
  lib/netstd/Thrift/Protocol/TJSONProtocol.cs
  lib/netstd/Thrift/Protocol/TMultiplexedProtocol.cs
  lib/netstd/Thrift/Protocol/ToString.cs
  lib/netstd/Thrift/Protocol/Utilities/TBase64Utils.cs
  lib/netstd/Thrift/Protocol/Utilities/TGuidExtensions.cs
  lib/netstd/Thrift/Protocol/Utilities/TJsonProtocolConstants.cs
  lib/netstd/Thrift/Server/TServer.cs
  lib/netstd/Thrift/Server/TSimpleAsyncServer.cs
  lib/netstd/Thrift/Thrift.csproj
  lib/netstd/Thrift/Transport/Client/TTlsSocketTransport.cs
  lib/netstd/Thrift/Transport/Layered/TFramedTransport.cs
  lib/netstd/Thrift/Transport/Layered/TLayeredTransport.cs
  lib/netstd/Thrift/Transport/Server/TNamedPipeServerTransport.cs
  lib/netstd/Thrift/Transport/Server/TServerSocketTransport.cs
  lib/netstd/Thrift/Transport/Server/TServerTransport.cs
  lib/netstd/Thrift/Transport/TTransport.cs
  test/netstd/Client/Client.csproj
  test/netstd/Client/Performance/PerformanceTests.cs
  test/netstd/Client/TestClient.cs
  test/netstd/Server/Server.csproj
  test/netstd/Server/TestServer.cs
  tutorial/netstd/Client/Client.csproj
  tutorial/netstd/Interfaces/Interfaces.csproj
  tutorial/netstd/Server/Server.csproj
Labels: c#

#2889 THRIFT-5746 Upgrade to net8 (continued)
  lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj
  lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj
  lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
  lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj
  lib/netstd/Thrift/Thrift.csproj
  test/netstd/Client/Client.csproj
  test/netstd/Server/Server.csproj
  tutorial/netstd/Interfaces/Interfaces.csproj
Labels: c#

#2887 THRIFT-5747 warning: The macro `AC_HELP_STRING' is obsolete. You should run autoupdate.
  aclocal/ax_thrift_internal.m4
  configure.ac
  contrib/fb303/aclocal/ax_thrift_internal.m4
Labels: build
