Repository apache/thrift, pull requests merged in 2023-02, with the labels that each got.

#2748 Update supported go versions
  .github/workflows/build.yml
  LANGUAGES.md
  build/docker/ubuntu-bionic/Dockerfile
  build/docker/ubuntu-focal/Dockerfile
  build/docker/ubuntu-jammy/Dockerfile
  go.mod
  lib/go/test/fuzz/go.mod
  lib/go/test/go.mod
  test/go/go.mod
Labels: golang

#2753 go: Use new atomic types introduced in go1.19
  lib/go/thrift/serializer_test.go
  lib/go/thrift/simple_server.go
  lib/go/thrift/socket_conn.go
Labels: golang

#2758 fix typo
  doc/specs/thrift-binary-protocol.md
Labels: doc

#2757 THRIFT-5684 upgrade to net7.0
  build/docker/README.md
  build/docker/old/debian-stretch/Dockerfile
  build/docker/old/ubuntu-artful/Dockerfile
  build/docker/old/ubuntu-disco/Dockerfile
  build/docker/old/ubuntu-xenial/Dockerfile
  build/docker/ubuntu-bionic/Dockerfile
  build/docker/ubuntu-focal/Dockerfile
  build/docker/ubuntu-jammy/Dockerfile
  compiler/cpp/src/thrift/generate/t_netstd_generator.cc
  configure.ac
  lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj
  lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj
  lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
  lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj
  lib/netstd/Thrift/Thrift.csproj
  lib/netstd/Thrift/Transport/Server/TNamedPipeServerTransport.cs
  test/netstd/Client/Client.csproj
  test/netstd/Client/TestClient.cs
  test/netstd/Server/Server.csproj
  test/netstd/Server/TestServer.cs
  tutorial/netstd/Client/Client.csproj
  tutorial/netstd/Interfaces/Interfaces.csproj
  tutorial/netstd/Server/Program.cs
  tutorial/netstd/Server/Server.csproj
Labels: c#

#2759 THRIFT-5685: Revert "THRIFT-5601: Fix forward typedef in go compiler"
  compiler/cpp/src/thrift/generate/t_go_generator.cc
  compiler/cpp/src/thrift/generate/t_go_generator.h
  lib/go/test/ForwardType.thrift
  lib/go/test/Makefile.am
  lib/go/test/tests/forwardtype_test.go
Labels: golang

#2760 Fix Security Tests for OpenSSLv3
  lib/cpp/test/SecurityFromBufferTest.cpp
  lib/cpp/test/SecurityTest.cpp
Labels: c++

#2762 Fix VisualStudio project files and upgrade to VS2015
  lib/cpp/libthrift.vcxproj
  lib/cpp/libthrift.vcxproj.filters
  lib/cpp/libthriftnb.vcxproj
  lib/cpp/libthriftnb.vcxproj.filters
Labels: c++

#2756 Fix MSVC warning C4706 (BinaryProtocol)
  lib/cpp/src/thrift/protocol/TBinaryProtocol.tcc
Labels: c++
