Repository apache/thrift, pull requests merged in 2023-06, with the labels that each got.

#2806 THRIFT-5709: Drastically improve to_string() performance.
  lib/cpp/src/thrift/TToString.h
Labels: compiler

#2819 THRIFT-5717 uuid sets and map keys may throw on some Haxe targets
  compiler/cpp/src/thrift/generate/t_haxe_generator.cc
Labels: haxe

#2818 THRIFT-5716: lib: cpp: Fix crash in TMemoryBuffer due to uint32_t overflow
  lib/cpp/src/thrift/transport/TBufferTransports.cpp
  lib/cpp/test/TMemoryBufferTest.cpp
Labels: c++

#2822 Fix typename for enum value in map for python gen code
  compiler/cpp/src/thrift/generate/t_py_generator.cc
  test/py/explicit_module/runtest.sh
  test/py/explicit_module/shared_types.thrift
  test/py/explicit_module/test4.thrift
Labels: python
