Repository apache/thrift, pull requests merged in 2024-07, with the labels that each got.

#2747 THRIFT-5678: lib: cpp: TConnectedClient: warning due to non-virtual dtor
  lib/cpp/src/thrift/TNonCopyable.h
  lib/cpp/src/thrift/async/TConcurrentClientSyncInfo.h
  lib/cpp/src/thrift/async/TEvhttpServer.h
  lib/cpp/src/thrift/transport/TFileTransport.h
  lib/cpp/src/thrift/windows/OverlappedSubmissionThread.h
  lib/cpp/src/thrift/windows/Sync.h
  lib/cpp/src/thrift/windows/TWinsockSingleton.h
Labels: c++

#3001 THRIFT-5795 namespace not properly escaped
  compiler/cpp/src/thrift/generate/t_netstd_generator.cc
  lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
  lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift5795.thrift
Labels: c#

#3003 CI/appveyor: fix download location for flex-sdk
  build/appveyor/MSVC-appveyor-full.bat
Labels: build and general CI

#3005 THRIFT-5797 HashSet() CTOR takes no argument for net < 5
  compiler/cpp/src/thrift/generate/t_netstd_generator.cc
Labels: c#

#3006 THRIFT-5796 Indicate target environment via #if check
  compiler/cpp/src/thrift/generate/t_netstd_generator.cc
  lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
  tutorial/netstd/Interfaces/Interfaces.csproj
Labels: c#

#3011 THRIFT-5800: Make non-exist include a failure when -strict is on
  compiler/cpp/src/thrift/main.cc
Labels: compiler
