Repository apache/thrift, pull requests merged in 2024-06, with the labels that each got.

#2980 Update compact-protocol docs [skip ci]
  doc/specs/thrift-compact-protocol.md
Labels: doc

#2985 go: Fix indentation in compiler
  compiler/cpp/src/thrift/generate/t_go_generator.cc
Labels: golang

#2984 go: Improve efficiency with zlib in THeaderTransport
  lib/go/thrift/header_transport.go
Labels: golang

#2975 optimizing performance issues under large-scale connection
  lib/cpp/src/thrift/server/TNonblockingServer.cpp
  lib/cpp/src/thrift/server/TNonblockingServer.h
Labels: c++

#2961 THRIFT-5777: python fix mismatched timeout exceptions.
  lib/py/src/transport/TSocket.py
  lib/py/test/test_socket.py
  lib/py/test/test_sslsocket.py
Labels: python

#2962 Use pip install instead of deprecated python setup.py install command
  lib/py/Makefile.am
Labels: python
