Repository apache/thrift, pull requests merged in 2024-11, with the labels that each got.

#3036 add loongarch info from http://www.gnu.org/software/autoconf-archive
  aclocal/ax_boost_base.m4
Labels: build and general CI

#3030 remove dependency on Six
  .github/workflows/build.yml
  build/appveyor/MSVC-appveyor-full.bat
  build/docker/ubuntu-focal/Dockerfile
  build/docker/ubuntu-jammy/Dockerfile
  contrib/Vagrantfile
  debian/control
  lib/nodejs/examples/httpServer.py
  lib/py/setup.py
  lib/py/src/TSCons.py
  lib/py/src/protocol/TProtocol.py
  lib/py/src/server/THttpServer.py
  lib/py/src/server/TNonblockingServer.py
  lib/py/src/server/TServer.py
  lib/py/src/transport/THttpClient.py
Labels: python

#3043 THRIFT-5775 Kotlin build failed for broken toolchain in docker
  build/docker/README.md
  lib/kotlin/build.gradle.kts
  lib/kotlin/cross-test-client/build.gradle.kts
  lib/kotlin/cross-test-server/build.gradle.kts
Labels: kotlin

#3059 THRIFT-5829 - Update TConstant.php to remove deprecated PHP code
  lib/php/lib/Type/TConstant.php
Labels: php

#3044 use 24.04 for github ci jobs
  .github/workflows/build.yml
Labels: build and general CI

#2679 GitHub cmake workflow to build libraries as well [skip ci]
  .github/workflows/cmake.yml
Labels: build and general CI

#3063 THRIFT-5833: Add ProcessorError
  compiler/cpp/src/thrift/generate/t_go_generator.cc
  lib/go/test/tests/processor_middleware_test.go
  lib/go/thrift/processor_factory.go
  lib/go/thrift/simple_server_test.go
Labels: golang

#3065 THRIFT-5836 No rule to make target 'Thrift5272.thrift', needed by 'gen-cpp/Thrift5272_types.h'
  lib/cpp/test/Makefile.am
Labels: c++, build and general CI
