Repository apache/thrift, pull requests merged in 2024-05, with the labels that each got.

#2972 THRIFT-5783 drop net7 support
  lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj
  lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj
  lib/netstd/Tests/Thrift.PublicInterfaces.Compile.Tests/Thrift.PublicInterfaces.Compile.Tests.csproj
  lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj
  lib/netstd/Thrift/Thrift.csproj
  test/netstd/Client/Client.csproj
  test/netstd/Server/Server.csproj
  tutorial/netstd/Interfaces/Interfaces.csproj
Labels: c#

#2974 go: Use errors.Is over ==
  lib/go/thrift/header_transport.go
  lib/go/thrift/simple_json_protocol.go
Labels: golang

#2973 THRIFT-5784: Add THeaderTransforms to TConfiguration
  lib/go/test/tests/header_zlib_test.go
  lib/go/thrift/configuration.go
  lib/go/thrift/header_protocol.go
  lib/go/thrift/header_protocol_test.go
  lib/go/thrift/header_transport.go
Labels: golang

#2978 Remove deprecated has_rdoc from gemspec
  lib/rb/thrift.gemspec
Labels: ruby

#2977 THRIFT-5786: Full deprecation support in go
  compiler/cpp/src/thrift/generate/t_go_generator.cc
  compiler/cpp/src/thrift/generate/t_go_generator.h
Labels: golang
