Repository apache/thrift, pull requests merged in 2024-08, with the labels that each got.

#3010 THRIFT-4847: CancelledKeyException causes TThreadedSelectorServer to fail
  lib/java/src/main/java/org/apache/thrift/server/AbstractNonblockingServer.java
  lib/java/src/main/java/org/apache/thrift/server/TThreadedSelectorServer.java
Labels: java

#2940 THRIFT-5706: lib/cpp Fix the Security tests on openssl 1.1 and 3.0
  lib/cpp/test/SecurityFromBufferTest.cpp
  lib/cpp/test/SecurityTest.cpp
Labels: c++

#3018 Update supported go versions
  .github/workflows/build.yml
  LANGUAGES.md
  go.mod
  lib/go/test/fuzz/go.mod
  lib/go/test/go.mod
  lib/go/test/tests/equals_test.go
  lib/go/test/tests/string_parse_allocation_test.go
  lib/go/test/tests/validate_test.go
  lib/go/thrift/binary_protocol_test.go
  lib/go/thrift/exception.go
  lib/go/thrift/framed_transport_test.go
  lib/go/thrift/header_transport.go
  lib/go/thrift/header_transport_test.go
  lib/go/thrift/json_protocol_test.go
  lib/go/thrift/lowlevel_benchmarks_test.go
  lib/go/thrift/protocol.go
  lib/go/thrift/protocol_test.go
  lib/go/thrift/serializer_test.go
  lib/go/thrift/serializer_types_test.go
  lib/go/thrift/simple_json_protocol.go
  lib/go/thrift/simple_json_protocol_test.go
  lib/go/thrift/ssl_server_socket.go
  lib/go/thrift/transport_test.go
  test/go/go.mod
  test/go/src/bin/stress/main.go
  test/go/src/bin/testclient/main.go
  test/go/src/bin/testserver/main.go
  test/go/src/common/client.go
  test/go/src/common/clientserver_test.go
  test/go/src/common/context_test.go
  test/go/src/common/server.go
Labels: golang

#3019 Fix failed java build
  lib/java/src/main/java/org/apache/thrift/server/AbstractNonblockingServer.java
  lib/java/src/main/java/org/apache/thrift/server/TThreadedSelectorServer.java
Labels: java

#3021 go: Fix cross test server
  test/go/src/bin/testserver/main.go
  test/go/src/common/server.go
Labels: golang

#3025 Fix python build on Github Actions
  .github/workflows/build.yml
Labels: python, github_actions

#3029 THRIFT-5813: Close the socket in TSocket.isOpen() when peek() fails
  lib/py/src/transport/TSocket.py
  lib/py/test/test_socket.py
Labels: python

#3014 Fix JS property/method collisions for fields named read/write
  compiler/cpp/src/thrift/generate/t_js_generator.cc
Labels: nodejs

#3016 THRIFT-5810: install static MSVC libraries to lib/
  build/cmake/DefineInstallationPaths.cmake
Labels: c++
