Repository apache/thrift, pull requests merged in 2025-05, with the labels that each got.

#3142 [nit] Use more consistent free method in c_glib generated code for binary types
  compiler/cpp/src/thrift/generate/t_c_glib_generator.cc
Labels: c_glib

#3145 Put field name in error message for set duplication check on write
  compiler/cpp/src/thrift/generate/t_go_generator.cc
Labels: golang

#3146 Fix received keyword
  lib/js/src/thrift.js
Labels: javascript

#3143 THRIFT-5869: Close the transport after TServerEventHandler deleteContext
  lib/java/src/main/java/org/apache/thrift/server/AbstractNonblockingServer.java
  lib/java/src/main/java/org/apache/thrift/transport/sasl/NonblockingSaslHandler.java
Labels: java

#3148 swift CI broken & no maintainer around to fix (temporary workaround re THRIFT-5864 )
  .github/workflows/build.yml
Labels: swift

#3154 Fix cross-test
  .github/workflows/build.yml
  test/test.py
Labels: github_actions

#3153 go: Add a zlib reader pool
  lib/go/thrift/compact_protocol_test.go
  lib/go/thrift/header_transport.go
  lib/go/thrift/pool.go
  lib/go/thrift/zlib_pool.go
  lib/go/thrift/zlib_pool_test.go
  lib/go/thrift/zlib_transport.go
Labels: golang
