Repository apache/thrift, pull requests merged in 2025-06, with the labels that each got.

#3155 THRIFT-5873: py: fix client auth support for THttpClient
  lib/py/src/transport/THttpClient.py
Labels: python

#3159 THRIFT-5874 Introduce new type MESSAGE_SIZE_LIMIT in TTransportException
  lib/netstd/Thrift/Protocol/TJSONProtocol.cs
  lib/netstd/Thrift/Transport/Client/THttpTransport.cs
  lib/netstd/Thrift/Transport/TEndpointTransport.cs
  lib/netstd/Thrift/Transport/TTransportException.cs
Labels: c#

#3163 added TMemoryStream to hx
  lib/haxe/src/org/apache/thrift/transport/TMemoryStream.hx
Labels: haxe

#3122 Erlang generator improvements for enum and type
  compiler/cpp/src/thrift/generate/t_erl_generator.cc
Labels: erlang

#3150 [nit] Adjust base64 padding parsing in TJSONProtocol
  lib/cpp/src/thrift/protocol/TJSONProtocol.cpp
  lib/cpp/test/JSONProtoTest.cpp
Labels: c++

#3165 THRIFT-5698: remove use of deprecated std::iterator
  lib/cpp/src/thrift/Thrift.h
  lib/cpp/src/thrift/transport/TSocketUtils.h
Labels: c++

#3152 Generate swap noexcept
  compiler/cpp/src/thrift/generate/t_cpp_generator.cc
Labels: c++

#3169 nuget package update
  lib/netstd/Benchmarks/Thrift.Benchmarks/Thrift.Benchmarks.csproj
  lib/netstd/Tests/Thrift.Compile.Tests/Thrift.Compile.net8/Thrift.Compile.net8.csproj
  lib/netstd/Tests/Thrift.Compile.Tests/Thrift.Compile.net9/Thrift.Compile.net9.csproj
  lib/netstd/Tests/Thrift.IntegrationTests/Thrift.IntegrationTests.csproj
  lib/netstd/Tests/Thrift.Tests/Thrift.Tests.csproj
  lib/netstd/Thrift/Thrift.csproj
  test/netstd/Client/Client.csproj
  test/netstd/Server/Server.csproj
  tutorial/netstd/Client/Client.csproj
  tutorial/netstd/Interfaces/Interfaces.csproj
Labels: c#
