Repository apache/thrift, pull requests merged in 2025-01, with the labels that each got.

#3080 Update generated array style
  compiler/cpp/src/thrift/generate/t_java_generator.cc
Labels: java

#3078 THRIFT-5842: Add missing cstdint include for int64_t in Mutex.h
  lib/cpp/src/thrift/concurrency/Mutex.h
Labels: c++

#3086 THRIFT-5845: Return TException for union check in Write
  compiler/cpp/src/thrift/generate/t_go_generator.cc
  lib/go/test/UnionBinaryTest.thrift
  lib/go/test/tests/write_texception_test.go
Labels: golang

#3082 THRIFT-5564: Add nodejs tests to github actions
  .github/workflows/build.yml
  lib/nodejs/lib/thrift/thrift.js
  lib/nodejs/test/deep-constructor.test.js
Labels: nodejs

#3085 THRIFT-5819: use latest rustc version for rustlib
  .github/workflows/build.yml
  LANGUAGES.md
  build/docker/README.md
  build/docker/ubuntu-focal/Dockerfile
  build/docker/ubuntu-jammy/Dockerfile
  compiler/cpp/src/thrift/generate/t_rs_generator.cc
  lib/rs/src/lib.rs
  lib/rs/src/protocol/compact.rs
  lib/rs/src/protocol/stored.rs
  lib/rs/src/transport/framed.rs
  rust-toolchain
  test/rs/src/bin/test_client.rs
Labels: rust

#3079 remove more Python2 compatibility
  compiler/cpp/test/compiler/staleness_check.py
  contrib/fb303/py/fb303_scripts/fb303_simple_mgmt.py
  lib/java/src/test/java/org/apache/thrift/test/EqualityTest.java
  lib/py/setup.py
  lib/py/src/TRecursive.py
  lib/py/src/TTornado.py
  lib/py/src/compat.py
  lib/py/src/protocol/TJSONProtocol.py
  lib/py/src/protocol/TProtocol.py
  lib/py/src/transport/TTransport.py
  lib/py/src/transport/TZlibTransport.py
  lib/py/test/thrift_json.py
  test/crossrunner/compat.py
  test/crossrunner/report.py
  test/py/FastbinaryTest.py
  test/py/RunClientServer.py
  test/py/SerializationTest.py
  test/py/TestClient.py
  test/py/TestServer.py
  test/test.py
Labels: python

#3072 lib/cpp/test/CMakeLists.txt: Fix building with OpenBSD
  lib/cpp/test/CMakeLists.txt
Labels: build and general CI

#3090 Upstream mingw capitalization patch
  lib/cpp/src/thrift/transport/THttpServer.cpp
  lib/cpp/src/thrift/transport/TPipeServer.cpp
  lib/cpp/src/thrift/transport/TServerSocket.cpp
  lib/cpp/src/thrift/transport/TWebSocketServer.h
  lib/cpp/src/thrift/windows/SocketPair.cpp
  lib/cpp/src/thrift/windows/Sync.h
Labels: c++
