Repository apache/thrift, pull requests merged in 2025-08, with the labels that each got.

#3182 Fix C++ build
  lib/cpp/src/thrift/Thrift.h
  lib/cpp/src/thrift/transport/TSocketUtils.h
Labels: c++

#3186 THRIFT-5855: Add FUZZING.md and test structures
  FUZZING.md
  test/FuzzTest.thrift
  test/v0.16/FuzzTestNoUuid.thrift
Labels: testsuite

#3167 THRIFT-5877: Add cpp cross tests
  .github/workflows/build.yml
  lib/cpp/src/thrift/protocol/THeaderProtocol.cpp
  lib/cpp/src/thrift/protocol/THeaderProtocol.h
  lib/cpp/src/thrift/protocol/TProtocolTap.h
  test/cpp/Makefile.am
  test/cpp/src/TestClient.cpp
  test/known_failures_Linux.json
Labels: c++

#3194 Add support for boringssl
  lib/cpp/src/thrift/transport/TSSLSocket.cpp
Labels: build and general CI
