Repository apache/thrift, pull requests merged in 2025-04, with the labels that each got.

#3119 Change SSL_get_verify_result() return value from int to long
  lib/cpp/src/thrift/transport/TSSLSocket.cpp
Labels: c++

#3115 THRIFT-5858: Introduce new type MESSAGE_SIZE_LIMIT in TTransportExcep…
  lib/java/src/main/java/org/apache/thrift/transport/TEndpointTransport.java
  lib/java/src/main/java/org/apache/thrift/transport/TTransportException.java
  lib/java/src/test/java/org/apache/thrift/protocol/ProtocolTestBase.java
  lib/java/src/test/java/org/apache/thrift/transport/TestTByteBuffer.java
Labels: java

#3120 Erlang generator improvements
  compiler/cpp/src/thrift/generate/t_erl_generator.cc
Labels: erlang

#3121 THRIFT-5861: Add isOpen method to TTornadoStreamTransport
  lib/py/src/TTornado.py
Labels: python

#3124 Remove ubuntu-20.04 from github actions
  .github/workflows/build.yml
Labels: github_actions

#3125 Fix field stop read in duplicate_protocol.go
  lib/go/thrift/duplicate_protocol.go
  lib/go/thrift/duplicate_protocol_test.go
Labels: golang

#3128 TestTServletServer doesn't accept the request
  lib/java/src/crossTest/java/org/apache/thrift/test/TestTServletServer.java
Labels: java

#3126 THRIFT-5860: Update minimum required CMake version for CMake 4.0 compatibility
  CMakeLists.txt
  compiler/cpp/CMakeLists.txt
  compiler/cpp/tests/CMakeLists.txt
Labels: build and general CI

#2728 Add Package.swift to root of repo
  Package.swift
Labels: swift
