Repository apache/thrift, pull requests merged in 2025-03, with the labels that each got.

#3108 THRIFT-5847: http.client.HTTPSConnection: drop key_file, cert_file
  lib/py/src/transport/THttpClient.py
Labels: python

#3099 THRIFT-5853: Remove oldstyle casts from TBufferTransports and TCompactProtocol
  lib/cpp/src/thrift/protocol/TCompactProtocol.h
  lib/cpp/src/thrift/protocol/TCompactProtocol.tcc
  lib/cpp/src/thrift/protocol/TProtocol.h
  lib/cpp/src/thrift/transport/TBufferTransports.cpp
  lib/cpp/src/thrift/transport/TBufferTransports.h
Labels: rebase needed, c++

#3112 Exclude binary dir in cmake when BUILD_COMPILER is OFF
  build/cmake/ThriftConfig.cmake.in
Labels: build and general CI

#3116 THRIFT-5859: Generate a values iterator for enum types for go
  compiler/cpp/src/thrift/generate/t_go_generator.cc
  lib/go/test/tests/enum_values_test.go
Labels: golang
